#!/usr/bin/env groovy

pipeline {
   agent any
   stages {
       stage('Initialise') {
           steps {
                  sh 'rm -rf cloudnativeex'
                  sh 'git clone https://github.com/shreyach13/cloudnativeex.git'
                  echo "Initialising job - cloning repo"
                  dir("cloudnativeex/Packer/"){
                    sh 'pwd'
                  }
                }
           }
      stage('Validate') {
        steps {
        dir("cloudnativeex/Packer/"){
          sh 'pwd'
          sh 'ls -al'
          echo "Validating PACKER json..."
          sh 'packer validate ami.json > packer_validate_out.txt'
          sh 'cat packer_validate_out.txt'
        }
        }
      }
      stage('Build') {
        steps {
          dir("cloudnativeex/Packer/"){
            sh 'packer build ami.json > packer_build.txt'
            sh 'cat packer_build.txt'
          }
        }
      }

           }
           }
