#!/usr/bin/env groovy

pipeline {
   agent any
   stages {
       stage('Initialise') {
           steps {
                  sh 'rm -rf cloudnativeex'
                  sh 'git clone https://github.com/shreyach13/cloudnativeex.git'
                  echo "Initialising job - cloning repo"
                  dir("cloudnativeex/Packer/"){
                    sh 'pwd'
                  }
                }
           }
      stage('Validate') {
        steps {
        dir("cloudnativeex/Packer/"){
          sh 'pwd'
          echo "Validating PACKER json..."
          sh 'packer validate ami.json'
        }
        }
      }

           }
           }
